removed splay dynamic calibration, added splay scaling
JohnRThomas/OpenGloves-Firmware pull request #1
Opened 2022-04-25 08:48 UTC by Valsvirtuals

first initial draft for splay scaling,

still a bit wounky because there's no real calibration for the resting position, so i'm just using 
"#define ANALOG_MID (ANALOG_MAX / 2)" in the meantime but it can be off depending on your potentiometers and their placements 

for calibration it should behave a bit like this:

-1 press calib button

-2 wait X amount of time

-3 redord splay_values for each fingers independantly for Y number of loops and average
    (so 5 arrays of Y lenght, averaged into 5 variables)

-4 offset is average_splay_value - 2047 (<--this is also where we would put antother offset to compensate for the natural splay ingame if Dan doesn't want to bother doing it in the driver)
    (so 5 offsets, to be applied to their respective fingers on each loop,)

-5 apply offset to splay_value right before "splay_value = constrain(splay_value, 0, 4095);" line 96 in Finger.hpp

2022-04-30 21:26 UTC, JohnRThomas commented
Can you squash this into a single commit please?

2022-04-30 21:30 UTC, JohnRThomas requested changes

2022-04-30 21:30 UTC, JohnRThomas commented on firmware/lucidgloves-firmware/Config.h
> +// Splay Scaling
Please add new config define to control this new functionality and make it false by default.

#define ENABLE_SPLAY_SCALING false //Experimental: <Add a comment here>

2022-04-30 21:30 UTC, JohnRThomas commented on firmware/lucidgloves-firmware/Finger.hpp
> +    splay_value = map(new_splay_value, ANALOG_MID - DRIVER_MAX_ANGLE, ANALOG_MID + DRIVER_MAX_ANGLE, ANALOG_MID - POT_MAX_ANGLE, ANALOG_MID + POT_MAX_ANGLE);
Please leave the old functionality in place and protect this new feature with the define mentioned earlier.

#if ENABLE_SPLAY_SCALING
NEW CODE HERE
#else
OLD CODE HERE
#endif

2022-05-31 04:39 UTC, JohnRThomas commented
@Valsvirtuals Please try out https://github.com/JohnRThomas/OpenGloves-Firmware/tree/better-splay and see if it works as expected. Once you confirm, I'll close this pull request. (The commit is still under your name)

2022-06-04 00:56 UTC, JohnRThomas commented
This has been merged to the main branch

2022-06-04 10:42 UTC, Valsvirtuals commented
you can close this pull request

2022-06-04 10:42 UTC, closed without merging