Add support for I2C & connecting FFB Servos through PCA9685 16ch PWM Board
JohnRThomas/OpenGloves-Firmware pull request #9
Opened 2022-07-22 21:33 UTC by Roastlawyer

2022-07-23 07:25 UTC, Roastlawyer commented on open-gloves/Config.h
> +#define PCA_9685_MIN_SERVOPULSE 100 //(total range should probably be 100ish-600ish)  start with values of 125 ish for Min and 500 for max, slowly decrease and increase them respectivly ↓
A "PCA_9685_MIN_SERVOPULSE" value of 125 ticks and "PCA_9685_MAX_SERVOPULSE" of 500 ticks (out of 4096 per cycle) sends out a MinPulse that is about 600 microseconds and a MaxPulse of about 2400 microseconds (when using 50hz/20 millisecond PWM cycles)

2022-07-23 23:20 UTC, JohnRThomas requested changes
Please squash this into a single commit instead of 5.

2022-07-23 23:23 UTC, JohnRThomas commented on open-gloves/ForceFeedback.hpp
> +    #if USE_PCA9685_16CH_FOR_FFB
Can you abstract this to a class that matches the interface of Servo and turn on and off functionality via a different include similar to how Servo vs ESP32Servo works in the current code.

2022-07-24 12:27 UTC, Roastlawyer commented on open-gloves/ForceFeedback.hpp
> +    #if USE_PCA9685_16CH_FOR_FFB
I do not know how to do that, especially to allow the servo.attach to work in the way it does now. I might be able to condence down to servo.WRITE_FUNCTION(servo_Pin, SERVO_MIN) but I don't know how to replicate the caching "which pin to write to" behavior of servo.attach

2023-01-23 03:52 UTC, closed without merging